version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ./work:/home/work
    restart: always
    expose:
      - "8888"
    ports:
      - "127.0.0.1:8888:8888"
    command: jupyter-lab --ip 0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='' --notebook-dir=/home/work
